### PR TITLE
WIP: add support for Jekyll 3

### PR DESCRIPTION
**Pull request by parkr**
:wave: 

This may have to wait for Jekyll 3.0.1 due to my being dumb about hooks. but hey!

### CODE REVIEW

**Comment by tjkohli** [comment]
Any updates? Do you guys need some help? I've been emulating OS X 10.10 with Jekyll 2.x because of this.

**Comment by parkr** [comment]
> I've been emulating OS X 10.10 with Jekyll 2.x because of this.

It's just a warning, there's no error. You can still use this plugin with Jekyll 3.

**Comment by gjtorikian** [comment]
Should we push forward with this? Not sure what's left but #37 got bumped recently.

**Comment by parkr** [comment]
@gjtorikian The code looks OK I think? Was just a Jekyll issue.

**Comment by gjtorikian** [comment]
Travis seems p. mad: `NoMethodError: undefined method `spec' for nil:NilClass`

**Comment by gjtorikian** [comment]
Superseding via https://github.com/gjtorikian/jekyll-last-modified-at/pull/40.

**Pull request closed without merging**
