### PR TITLE
Use posix-spawn instead of Open3.

### PR DESCRIPTION
**Pull request by parkr**
Ok, honestly not sure how much this will improve things, but perhaps, perhaps, perhaps it will shave a few seconds off that 10s number. Would you mind testing with that site and reporting if there's any speed boost?

Best option would be to use C-bindings in Git... maybe use Rugged or something instead of shelling out at all? Who could we ask about that?

### CODE REVIEW

**Comment by parkr** [comment]
Still want this? Should be faster.

**Comment by gjtorikian** [comment]
*Why not?*

**Comment by parkr** [comment]
Looooool you're the greatest.

**Comment by parkr** [comment]
Thanks :heart:

**Pull request merged**
