### PR TITLE
Support Jekyll 3

### PR DESCRIPTION
**Pull request by gjtorikian**
Closes https://github.com/gjtorikian/jekyll-last-modified-at/issues/37, closes https://github.com/gjtorikian/jekyll-last-modified-at/issues/36.

### CODE REVIEW

**Comment by gjtorikian** [comment]
All the tests fail and I don't know why.

**Comment by parkr** [comment]
> All the tests fail and I don't know why.

Looks like all of them have new commit times?

**Comment by gjtorikian** [comment]
Indeed. But the tests pass locally. So I dunno how the dates all changed.

**Comment by oncleben31** [comment]
Is there any ETA for a version compatible with Jekyll 3 ?
Is there still blocking issue? If yes how can we help?

**Comment by gjtorikian** [comment]
Oh, I just had to make a few more changes.

**Pull request merged**
